name: Dumb Drop
services:
    dumbdrop:
        ports:
            - 3000:3000
        volumes:
            - ./local_uploads:/app/uploads
        environment:
            - DUMBDROP_PIN=123456
            - APPRISE_URL=          # i.e. tgram://bottoken/ChatID
            - APPRISE_MESSAGE=      # dont add quotes here
        image: abite3/dumbdrop:latest